Genesis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls'))
]

if settings.DEBUG:
    urlpatterns += static (settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    handler403 = 'user.views.error_403'
    handler404 = 'user.views.error_404'

user/urls.py
from django.urls import path
from .views import (Registration,
                    Login, 
                    Logout, 
                    index, 
                    ProfileView,
                    UpdateProfileView,
                    DeleteUserView,
                    PasswordChangeView,
                    PasswordResetView,
                    PasswordResetDoneView,
                    PasswordResetConfirmView,
                    PasswordResetCompleteView,
                    ClientRegistration)

from . import views


app_name = 'user'

urlpatterns = [
    path('clientRegister/', ClientRegistration.as_view(), name='client_registration'),
    path('register/', Registration.as_view(), name='register'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('index/', index.as_view(), name='index'),
    path('profile/<int:pk>', ProfileView.as_view(), name='profile'),
    path('update_profile/<int:pk>', UpdateProfileView.as_view(), name='update_profile'),
    path('delete_user/<int:pk>', DeleteUserView.as_view(), name='delete_user'),
    path('change_password/', PasswordChangeView.as_view(), name='change_password'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

user/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm

from .models import customUser
from .validator import validate_email, validate_username
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import authenticate
from .models import Profile


class UserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""

    username = forms.CharField(validators = [validate_username], required=True, label= 'Username', widget = forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(validators = [validate_email], required=True, label= "Email", widget = forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(
        required=True,  
        help_text = mark_safe(_(
            '<ul class="light " style="list-style-type: square;"><li style="margin-left: -10px">    <small id="hint_id_password1" class=" d-block form-text text-muted"> Password must contain at least 8 characters.    </small> </li><li style="margin-left: -10px"> <small id="hint_id_password1" class=" d-block form-text text-muted"> Password can’t be a commonly used password.</small> </li><li style="margin-left: -10px">    <small id="hint_id_password1" class=" d-block form-text text-muted"> Password can’t be too similar to your other personal information.</small> </li><li style="margin-left: -10px"><small id="hint_id_password1" class=" d-block form-text text-muted"> Password can’t be entirely numeric.</small></li></ul>'
        ))
        , label= "Password",  widget = forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label=_("Confirm Password"), widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = customUser
        fields = '__all__'
        exclude = ['last_login', 'password', 'is_admin']

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords don't match")
        return password2

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)

        # for not displaying help text 
        for fieldname in ['username', 'password2']:
            self.fields[fieldname].help_text = None

        # adding class to password2 field
        self.fields['password2'].widget.attrs['class'] = 'form-control'

        # for placeholder
        self.fields['username'].widget.attrs['placeholder'] = 'Example: Genesis'
        self.fields['email'].widget.attrs['placeholder'] = 'Example@gmail.com'

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.username = (self.cleaned_data["username"])
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class normalUserCreation(UserCreationForm):
    class Meta:
        model = customUser
        fields = ['username', 'email', 'password1', 'password2']

class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = customUser
        fields = ('email', 'username', 'password', 'is_active', 'is_admin')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class UserLoginForm(AuthenticationForm):

    username = forms.CharField(max_length=254)
    password = forms.CharField(label=_("Password"), widget=forms.PasswordInput)

    error_messages = {
        'invalid_login': _("Please enter a correct %(username)s and password. "
                           "Note that both fields may be case-sensitive."),
        'inactive': _("This account is inactive."),
    }

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username,
                                           password=password)
            if user is None:
                raise forms.ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login', 
                    params={'username': self.username_field.verbose_name},
                )
                
            if not user.is_active:
                raise forms.ValidationError(
                    self.error_messages['inactive'],
                    code='inactive',
                )

        return self.cleaned_data        
    
    def get_user_id(self):
        if self.user_cache:
            return self.user_cache.id
        return None

    def get_user(self):
        return self.user_cache

class ProfileUpdateForm(forms.ModelForm):
    
    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['user',]

class passwordChangeForm(PasswordChangeForm):

    old_password = forms.CharField(label=_("Old Password"), widget=forms.PasswordInput)
    new_password1 = forms.CharField(label=_("New Password"),help_text = mark_safe(_(
            '<ul class="light " style="list-style-type: square;"><li style="margin-left: -10px">    <small id="hint_id_password1" class=" d-block form-text text-muted"> Password must contain at least 8 characters.    </small> </li><li style="margin-left: -10px"> <small id="hint_id_password1" class=" d-block form-text text-muted"> Password can’t be a commonly used password.</small> </li><li style="margin-left: -10px">    <small id="hint_id_password1" class=" d-block form-text text-muted"> Password can’t be too similar to your other personal information.</small> </li><li style="margin-left: -10px"><small id="hint_id_password1" class=" d-block form-text text-muted"> Password can’t be entirely numeric.</small></li></ul>'
        )),
        widget=forms.PasswordInput)
    new_password2 = forms.CharField(label=_("Confirm Password"), widget=forms.PasswordInput)

    class Meta:
        model = customUser
        fields = ('old_password', 'new_password1', 'new_password2')

user/views.py
from django.shortcuts import redirect, render
from django.views.generic import (View, 
								  CreateView, 
								  UpdateView,
								  DetailView,
								  DeleteView,
								  TemplateView,
								  FormView)

from .forms import (UserCreationForm, 
					UserLoginForm, 
					normalUserCreation, 
					ProfileUpdateForm,
					passwordChangeForm)

from django.contrib.auth import (
							authenticate,
							login,
							logout)

from django.contrib.auth.views import (
								PasswordChangeView, 
								PasswordResetView,
								PasswordResetDoneView,
								PasswordResetConfirmView,
								PasswordResetCompleteView)
									
from django.urls import reverse_lazy
from django.http.response import HttpResponseRedirect
from Genesis import settings
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from django.utils.http import is_safe_url, urlsafe_base64_encode
from django.contrib.auth.views import redirect_to_login
from django.http import Http404

# for token generation
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm

from .models import customUser, Profile
from .mixins import NextUrlMixin

# to access system varibale
import os
from django.core.mail import EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes

# permission denied custom template
def error_403(request, exception):
        data = {'forbiddenUser': request.user}
        return render(request,'user/403.html', data)

# page not found
def error_404(request, exception):
        data = {}
        return render(request,'user/404.html', data)

class Registration(SuccessMessageMixin, CreateView):
	form_class = normalUserCreation
	template_name = 'user/Registration.html'
	success_url = reverse_lazy('user:login')
	success_message = "Account for %(username)s was created successfully"

	def form_valid(self, form):
		user = form.save(commit=False)
		user.save()
		mail_subject = 'Registration Successful.'
		message = render_to_string('user/welcome_email.html', {
			'user': user,
		})
		to_email = form.cleaned_data.get('email')
		email = EmailMessage(
			mail_subject, message, to=[to_email]
		)
		email.send()
		return super(Registration, self).form_valid(form)

class ClientRegistration(SuccessMessageMixin, CreateView):
	form_class = UserCreationForm
	template_name = 'user/Registration.html'
	success_url = reverse_lazy('user:login')
	success_message = "Account for %(username)s was created successfully"


class Login(NextUrlMixin, FormView):
	form_class= UserLoginForm
	template_name = 'user/Login.html'
	success_url = reverse_lazy('user:index')
		
	# function to redirect to next url
	# def get_next_url(self):
	# 	next_ = self.request.GET.get('redirect_to')
	# 	next_post = self.request.POST.get('redirect_to')
	# 	redirect_path = next_ or next_post or None
	# 	if is_safe_url(redirect_path, self.request.get_host()):
	# 		return redirect_path

	# 	return self.get_success_url()
		
	def form_valid(self, form):
		username=form.cleaned_data.get('username')
		password = form.cleaned_data.get('password')
		user = authenticate(username=username, password=password)
		login(self.request, user)

		return HttpResponseRedirect(self.get_next_url())

	# for already logged user
	def get(self, request, *args, **kwargs):
		if request.user.is_authenticated:
			return redirect(settings.LOGIN_REDIRECT_URL)
		return super(Login, self).get(request, *args, **kwargs)

class Logout(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(settings.LOGIN_URL)

class index(TemplateView):
    template_name = 'base.html'

# ----------------------------PROFILE-------------------------------

class ProfileView(LoginRequiredMixin,DetailView):
	model = Profile
	template_name = 'user/Profile.html'
	login_url = 'user:login'
	redirect_field_name = 'redirect_to'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['userProfile'] = Profile.objects.get(pk = self.kwargs['pk'])
		return context

class UpdateProfileView(UserPassesTestMixin, LoginRequiredMixin, UpdateView):
	model = Profile
	form_class = ProfileUpdateForm
	template_name = 'user/UpdateProfile.html'
	pk_url_kwarg = 'pk'
	login_url = 'user:login'
	redirect_field_name = 'redirect_to'

	def test_func(self):
		obj = self.get_object()
		if obj.user == self.request.user:
			return True
		return False

	def get_object(self, queryset=None):
		profile = self.model.objects.get(pk= self.kwargs['pk'])
		return profile

	def get_success_url(self):
		return reverse_lazy('user:profile', kwargs={'pk': self.object.pk})

class DeleteUserView(UserPassesTestMixin, LoginRequiredMixin, DeleteView):
	model = customUser
	context_object_name = 'user'
	pk_url_kwarg = 'pk'
	template_name = 'user/confirm_delete_user.html'
	success_url = reverse_lazy('user:index')
	login_url = 'user:login'
	redirect_field_name = 'redirect_to'

	def test_func(self):
		obj = self.get_object()
		return obj == self.request.user
 
	def get_object(self, queryset=None):
		user = self.model.objects.get(pk= self.kwargs['pk'])
		return user

# ---------------------- Password change ----------------------
class PasswordChangeView(LoginRequiredMixin, PasswordChangeView):
	model = customUser
	form_class = passwordChangeForm
	template_name = 'user/passwordChange.html'
	success_url = reverse_lazy('user:login') 
	login_url = 'user:login'
	redirect_field_name = 'redirect_to'

class PasswordResetView(PasswordResetView):
	template_name = 'user/password_reset.html'
	email_template_name = 'user/password_reset_email.html'
	# subject_template_name = 'user/password_reset_subject.txt'
	form_class = PasswordResetForm
	from_email = settings.EMAIL_HOST_USER
	token_generator = default_token_generator
	html_email_template_name = None
	extra_email_context = None
	success_url = reverse_lazy('user:password_reset_done')

	# backend process of password rest view  

	# def form_valid(self, form):
	# 	opts = {
	# 		'use_https': self.request.is_secure(),
	# 		'token_generator': self.token_generator,
	# 		'from_email': self.from_email,
	# 		'email_template_name': self.email_template_name,
	# 		# 'subject_template_name': self.subject_template_name,
	# 		'request': self.request,
	# 		'html_email_template_name': self.html_email_template_name,
	# 		'extra_email_context': self.extra_email_context,
	# 	}
	# 	form.save(**opts)
	# 	return super().form_valid(form)
	
	# def get_success_url(self):
	#  	return reverse_lazy('user:password_reset_done')

class PasswordResetDoneView(PasswordResetDoneView):
	template_name = 'user/password_reset_done.html'

class PasswordResetConfirmView(PasswordResetConfirmView):
	template_name = 'user/password_reset_confirm.html'
	form_class = SetPasswordForm
	token_generator = default_token_generator
	reset_url_token = 'set-password'
	post_reset_login = False
	success_url = reverse_lazy('user:password_reset_complete')

class PasswordResetCompleteView(PasswordResetCompleteView):
	template_name = 'user/password_reset_complete.html'

	

user/templates/user/ClientRegistration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="details">
        <!-- <p class="font-weight-normal h2">Create your Gencom Account</p> -->
    </div>
    <div class="login-direct">
        <a href="{% url 'login' %}">login</a>
    </div>
    <form method="POST" action="#">
        <div class="form-holder col-md-5 mt-3 mx-auto">
            <div class="form-group mb-2">
                {% csrf_token %}
    
                {{form|crispy}}
            </div>
            <button type="submit" class="btn btn-dark btn-block">Create User</button>
        </div>
    </form>
{% endblock %}

user/templates/user/Login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="col-md-7 mt-5  mx-auto">
        <div class="details p-4 text-white bg-dark">
            <p class="font-weight-normal h2 text-center">Enjoy Your Time</p>
        </div>

        <!-- <a href="{% url 'user:register' %}">register</a> -->
        
        {% if messages %}
            <div class="alert alert-success alert-dismissible fade show mt-3" role="alert">
                {% for message in messages %}
                    <strong id="messages">{{message}}</strong>
                {% endfor %} 
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
    
        <form method="POST" action="#">
            <div class="form-holder mt-3">
                <div class="form-group mb-2">
                    {% csrf_token %}
        
                    {{form|crispy}}
                </div>
                <div class="d-flex justify-content-end mb-3">
                    <a href="{% url 'user:password_reset' %}">Forget password</a>
                </div>
                <button type="submit" class="btn btn-dark btn-block">Sign In</button>
            </div>
        </form>	
    </div>
    
{% endblock %}

user/templates/user/Profile.html
{% extends 'base.html' %}

{% block content %}
    <div class="d-flex justify-content-end">
        <a href="{% url 'user:update_profile' userProfile.id %}" class="btn btn-success mr-3">Update</a>
        <a href="{% url 'user:delete_user' userProfile.user.pk %}" class="btn btn-danger mr-3">Delete</a>
        <a href="{% url 'user:change_password' %}" class="btn btn-primary ">change_password</a>    
    </div>
    <div class="mt-3">
        {{userProfile.user.username}}
        {{userProfile.user.email}}
        
        {% if userProfile.image%}
            <img src="{{ userProfile.imageURL }}" alt="">
        {% else %}
            no profile image
        {% endif %}
    </div>
    
{% endblock %}

user/templates/user/Registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="details">
        <!-- <p class="font-weight-normal h2">Create your Gencom Account</p> -->
    </div>
    <a href="{% url 'user:login' %}">Login</a>

    <form method="POST" action="#">
        <div class="form-holder col-md-7 mt-3 mx-auto">
            <div class="form-group mb-2">
                {% csrf_token %}
    
                {{form|crispy}}
            </div>
            <button type="submit" class="btn btn-dark btn-block">Sign Up</button>
        </div>
    </form>
{% endblock %}

user/templates/user/UpdateProfile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="details">
        <!-- <p class="font-weight-normal h2">Create your Gencom Account</p> -->
    </div>

    <form method="POST" action="#">
        <div class="form-holder col-md-7 mt-3 mx-auto">
            <div class="form-group mb-2">
                {% csrf_token %}
    
                {{form|crispy}}
            </div>
            <button type="submit" class="btn btn-dark btn-block">Update</button>
        </div>
    </form>
{% endblock %}

user/templates/user/confirm_delete_user.html
{% extends 'base.html' %}
{% block title %} Gencom | Delete Product {% endblock %}

{% block content%}
    <div class="h2">Delete Product</div>
<br>
    <form action="#" method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete '{{user}}?'</p>
        <button type="submit" class="btn btn-primary">Confirm</button>     <a href="{% url 'user:profile' user.profile.id %}" class= "btn btn-primary">cancel</a>

    </form>
{% endblock %}

user/templates/user/passwordChange.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h2 class="d-flex justify-content-center">Change password</h2>
    <form method="POST" action="#">
        <div class="form-holder col-md-7 mt-3 mx-auto">
            <div class="form-group mb-2">
                {% csrf_token %}
    
                {{form|crispy}}
            </div>
            <button type="submit" class="btn btn-dark btn-block">Change password</button>
        </div>
    </form>
{% endblock %} 

user/templates/user/password_reset.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  
    <form method="POST" action="#">
        <div class="form-holder col-md-7 mt-3 mx-auto">
            <div class="form-group mb-2">
                {% csrf_token %}
    
                {{form|crispy}}
            </div>
            <button type="submit" class="btn btn-dark btn-block">Submit</button>
        </div>
    </form>
{% endblock %}

user/templates/user/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
    <div class="alert alert-info">
        Your password has been set.
    </div>
    <a href="{% url 'user:login' %}">Sign In Here</a>
{% endblock content %}

user/templates/user/password_reset_confirm.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  
  <!--Password Reset Confirm-->
    <div class="container p-5">
	    <h2 class="font-weight-bold mt-3">Password Reset Confirm</h2>
		<hr>
        <p>Please enter your new password.</p>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}                    
            <button class="btn btn-primary" type="submit">Reset password</button>
        </form>
    </div>

{% endblock %}

user/templates/user/password_reset_done.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="alert alert-info">
        An email has been sent with instructions to reset your password
    </div>
{% endblock content %}

user/templates/user/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'user:password_reset_confirm' uidb64=uid token=token %}

user/templates/user/welcome_email.html
{% autoescape off %}  
Hi {{ user.username }},  Welcome!!!
http://localhost:8000{% url 'user:login' %}  
{% endautoescape %}