Genesis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls'))
]

if settings.DEBUG:
    urlpatterns += static (settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    handler403 = 'user.views.error_403'
    handler404 = 'user.views.error_404'

user/urls.py
from django.urls import path
from .views import (Registration,
                    Login, 
                    Logout, 
                    index, 
                    ProfileView,
                    UpdateProfileView,
                    DeleteUserView,
                    PasswordChangeView,
                    PasswordResetView,
                    PasswordResetDoneView,
                    PasswordResetConfirmView,
                    PasswordResetCompleteView,
                    ClientRegistration)

from . import views


app_name = 'user'

urlpatterns = [
    path('clientRegister/', ClientRegistration.as_view(), name='client_registration'),
    path('register/', Registration.as_view(), name='register'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('index/', index.as_view(), name='index'),
    path('profile/<int:pk>', ProfileView.as_view(), name='profile'),
    path('update_profile/<int:pk>', UpdateProfileView.as_view(), name='update_profile'),
    path('delete_user/<int:pk>', DeleteUserView.as_view(), name='delete_user'),
    path('change_password/', PasswordChangeView.as_view(), name='change_password'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


    <style>
        .asteriskField {
            display: none;
        }
    </style>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
      <div class="container">

          <!-- Image and text -->
          <nav class="navbar navbar-light bg-light">
              <a class="navbar-brand" href="#">
              <img src="{% static '/images/RDF.png' %}" width="30" height="30" class="d-inline-block align-top" alt="Gencom-logo">
              Gencom
              </a>
          </nav>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                  <li class="nav-item">
                      <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                  </li>
              </ul>

              <form class="form-inline my-2 my-lg-0 w-50" method="GET">
                  <input class="form-control mr-sm-2 w-100" type="search" placeholder="Search" aria-label="Search">
              </form>

              <ul class="navbar-nav ml-auto">
                  
                  {% if user.is_authenticated %}
                      <li class="nav-item">
                          <a class="nav-link" href="{% url 'user:profile' user.profile.id %}">Profile</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
                      </li>
                  {%else%}
                      <li class="nav-item">
                          <a class="nav-link" href="{% url 'user:register' %}">Sign up</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="{% url 'user:login' %}">Login</a>
                      </li>
                  {% endif %}
              </ul>
          </div>
      </div>
  </nav>

  <div class="container">
    {% block content %}
    {% endblock %}
  </div>

  {% block script%}
  {% endblock %}

  <script>
    // to remove '#' from url  
    window.onload = function() {
        history.replaceState(null, null, ' ');
    } 
  </script>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  </body>
</html>